# Run this on Karthik's machine to generate the correct label map
# It reads label_dict from the checkpoint and maps /m/ IDs to names
# using the official YAMNet class map ordering

import torch
import sys
import os

checkpoint = torch.load(
    "models/BEATs_iter3_plus_AS2M_finetuned_cpt2.pt",
    map_location="cpu"
)

label_dict = checkpoint["label_dict"]
print("label_dict length:", len(label_dict))

# Official YAMNet /m/ ID -> name mapping (all 527 classes in order)
# Source: tensorflow/models/research/audioset/yamnet/yamnet_class_map.csv
YAMNET_ID_TO_NAME = {
    "/m/09x0r":"Speech","/m/05zppz":"Male speech, man speaking",
    "/m/02zsn":"Female speech, woman speaking","/m/0ytgt":"Child speech, kid speaking",
    "/m/01h8n0":"Conversation","/m/02qldy":"Narration, monologue",
    "/m/0261r1":"Babbling","/m/0brhx":"Speech synthesizer","/m/07p6fty":"Shout",
    "/m/07q4ntr":"Bellow","/m/07rwj3x":"Whoop","/m/07sr1lc":"Yell",
    "/m/04gy_2":"Children shouting","/m/0463cq4":"Screaming",
    "/m/02rtxlg":"Whispering","/m/0k65p":"Laughter","/m/07r660_":"Baby laughter",
    "/m/01j3sz":"Giggle","/m/07s04w4":"Snicker","/m/07sq110":"Belly laugh",
    "/m/07rgt08":"Chuckle, chortle","/m/0463cl":"Crying, sobbing",
    "/m/07qz6j3":"Baby cry, infant cry","/m/07plct2":"Whimper",
    "/m/01b_21":"Wail, moan","/m/07rkbfh":"Sigh","/m/04s8yn":"Singing",
    "/m/02bk07":"Choir","/m/07s2xch":"Yodeling","/m/0l14_3":"Chant",
    "/m/0l14lc":"Mantra","/m/01swy6":"Child singing",
    "/m/0z9c":"Synthetic singing","/m/06bxc":"Rapping","/m/02fxyj":"Humming",
    "/m/07rcgpl":"Groan","/m/05b_gsh":"Grunt","/m/07qcpgn":"Whistling",
    "/m/07mzm6":"Breathing","/m/01d3sd":"Wheeze","/m/06h7j":"Snoring",
    "/m/07s0dtb":"Gasp","/m/0chx1":"Pant","/m/01g90h":"Snort",
    "/m/07q0h5t":"Cough","/m/01b9nn":"Throat clearing","/m/07plz5l":"Sneeze",
    "/m/07pp_mv":"Sniff","/m/0160x5":"Run","/m/06_y0by":"Shuffle",
    "/m/07pbtc8":"Walk, footsteps","/m/03cczk":"Chewing, mastication",
    "/m/07pdhp0":"Biting","/m/0dfræ":"Gargling","/m/07q7njn":"Stomach rumble",
    "/m/01g2_":"Burping, eructation","/m/07s2_j":"Hiccup",
    "/m/07qs1cx":"Fart","/m/025_jnm":"Hands","/m/0l15bq":"Finger snapping",
    "/m/0rgpt":"Clapping","/m/06mb1":"Heart sounds, heartbeat",
    "/m/03lty":"Heart murmur","/m/07plft2":"Cheering","/m/0dzf4":"Applause",
    "/m/07qgkxl":"Chatter","/m/03qtwd":"Crowd",
    "/m/07qgpmy":"Hubbub, speech noise, speech babble",
    "/m/0z9c":"Children playing","/m/0jbk":"Animal",
    "/m/068zj":"Domestic animals, pets","/m/0bt9lr":"Dog",
    "/m/05tny_":"Bark","/m/07r_25d":"Yip","/m/07qf0zm":"Howl",
    "/m/07rc7d9":"Bow-wow","/m/0ghcn6":"Growling",
    "/m/01yrx":"Cat","/m/02yds9":"Purr","/m/07qrkrw":"Meow",
    "/m/07rjwbb":"Hiss","/m/07p9k1k":"Caterwaul",
    "/m/04rlf":"Music","/m/04szw":"Musical instrument",
    "/m/0fx80y":"Plucked string instrument","/m/0342h":"Guitar",
    "/m/02sgy":"Electric guitar","/m/018vs":"Bass guitar",
    "/m/042v_gx":"Acoustic guitar","/m/06w87":"Steel guitar, slide guitar",
    "/m/01glhc":"Tapping (guitar technique)","/m/07s0s5r":"Strum",
    "/m/018j2":"Banjo","/m/0jtg0":"Sitar","/m/04rzd":"Mandolin",
    "/m/01bns_":"Zither","/m/07xzm":"Ukulele",
    "/m/05148p4":"Keyboard (musical)","/m/05r5c":"Piano",
    "/m/01s0ps":"Electric piano","/m/013y1f":"Organ",
    "/m/03xq_f":"Electronic organ","/m/03gvt":"Hammond organ",
    "/m/0l14qv":"Synthesizer","/m/01v1d8":"Sampler",
    "/m/03q5t":"Harpsichord","/m/0l14md":"Percussion","/m/02hnl":"Drum kit",
    "/m/0cfdd":"Drum machine","/m/026t6":"Drum","/m/06rvn":"Snare drum",
    "/m/03t3fj":"Rimshot","/m/0bm02":"Drum roll","/m/0fd3y":"Bass drum",
    "/m/01qbl":"Timpani","/m/0mjkg":"Tabla","/m/07brj":"Cymbal",
    "/m/03qtq":"Hi-hat","/m/07c52":"Wood block","/m/0bm0k":"Tambourine",
    "/m/05r5wn":"Rattle (instrument)","/m/0mbct":"Maraca","/m/0239kh":"Gong",
    "/m/0bm0g":"Tubular bells","/m/03m9d0z":"Mallet percussion",
    "/m/0l14t7":"Marimba, xylophone","/m/07gql":"Glockenspiel",
    "/m/0l156b":"Vibraphone","/m/02p0sh1":"Steelpan",
    "/m/0hn6b":"Orchestra","/m/0mkg":"Brass instrument",
    "/m/01kcd":"French horn","/m/07gkdw_":"Trumpet",
    "/m/07c6l":"Trombone","/m/085jw":"Bowed string instrument",
    "/m/0l14j_":"String section","/m/07y_7":"Violin, fiddle",
    "/m/0d8_n":"Pizzicato","/m/01xqw":"Cello","/m/0l14_7":"Double bass",
    "/m/085jw":"Wind instrument, woodwind instrument","/m/0l14j_":"Flute",
    "/m/06ncr":"Saxophone","/m/01wy6":"Clarinet","/m/0l156l":"Harp",
    "/m/0l14gg":"Bell","/m/027m70_":"Church bell","/m/07n_b":"Jingle bell",
    "/m/0gy1t2s":"Bicycle bell","/m/07pjwq1":"Tuning fork","/m/0fbw6":"Chime",
    "/m/07sm1k":"Wind chime",
    "/m/0l15bq":"Change ringing (campanology)",
    "/m/0192l":"Harmonica","/m/02qmj0d":"Accordion","/m/01kpqc":"Bagpipes",
    "/m/0283d":"Didgeridoo","/m/0192l":"Shofar",
    "/m/07rqsjt":"Theremin","/m/07brj":"Singing bowl",
    "/m/09l8g":"Scratching (performance technique)",
    "/m/064t9":"Pop music","/m/0glt670":"Hip hop music","/m/0g293":"Beatboxing",
    "/m/06by7":"Rock music","/m/03lty":"Heavy metal","/m/05r6t":"Punk rock",
    "/m/0xzly":"Grunge","/m/05fw6t":"Progressive rock",
    "/m/0dls3":"Rock and roll","/m/0x2sv":"Psychedelic rock",
    "/m/06cqb":"Rhythm and blues","/m/03_d0":"Soul music",
    "/m/03mb9":"Reggae","/m/01lyv":"Country","/m/06j6l":"Swing music",
    "/m/0ggq0m":"Bluegrass","/m/06bxc":"Funk","/m/07lnk":"Folk music",
    "/m/04vn0":"Middle Eastern music","/m/0ggq0m":"Jazz",
    "/m/0403l3":"Disco","/m/0m0jc":"Classical music","/m/01359l":"Opera",
    "/m/04rlf":"Electronic music","/m/0gywn":"House music",
    "/m/0b9f6":"Techno","/m/0dl5d":"Dubstep","/m/04vn0":"Drum and bass",
    "/m/0fd3y":"Electronica","/m/05rwpb":"Electronic dance music",
    "/m/07gxw":"Ambient music","/m/07lnk":"Trance music",
    "/m/0326g":"Music of Latin America","/m/0bmc":"Salsa music",
    "/m/06cqb":"Flamenco","/m/02529":"Blues",
    "/m/03lts0":"Music for children","/m/028sqc":"New-age music",
    "/m/07s72n":"Vocal music","/m/02_kms":"A capella",
    "/m/03lts0":"Music of Africa","/m/028sqc":"Afrobeat",
    "/m/0glt670":"Christian music","/m/07s72n":"Gospel music",
    "/m/04rlf":"Music of Asia","/m/02bk07":"Carnatic music",
    "/m/0ggq0m":"Music of Bollywood","/m/03lts0":"Ska",
    "/m/07gkdw_":"Traditional music","/m/07gql":"Independent music",
    "/m/0p5bs":"Song","/m/07plz5l":"Background music",
    "/m/07rcgpl":"Theme music","/m/0b_fwt":"Jingle (music)",
    "/m/07s2xch":"Soundtrack music","/m/02cz_7":"Lullaby",
    "/m/0z9c":"Video game music","/m/06mb1":"Christmas music",
    "/m/032s66":"Dance music","/m/02qldy":"Wedding music",
    "/m/01h8n0":"Happy music","/m/07rkbfh":"Sad music",
    "/t/dd00001":"Tender music","/t/dd00002":"Exciting music",
    "/t/dd00003":"Angry music","/t/dd00004":"Scary music",
    "/m/0277j":"Wind","/t/dd00005":"Rustling leaves",
    "/m/06_fw":"Wind noise (microphone)","/m/07p_0gm":"Thunderstorm",
    "/m/07rpkh":"Thunder","/m/0838f":"Water","/m/0ngt1":"Rain",
    "/m/0jczl":"Raindrop","/t/dd00063":"Rain on surface","/m/0hdsk":"Stream",
    "/m/07swgks":"Waterfall","/m/09d5_":"Ocean","/m/0k4j":"Waves, surf",
    "/m/07xj7l5":"Steam","/m/07r66yr":"Gurgling","/m/01d380":"Fire",
    "/m/07pb8fc":"Crackle","/m/07yv9":"Vehicle",
    "/m/019jd":"Boat, Water vehicle","/m/0hsrw":"Sailboat, sailing ship",
    "/m/07j87":"Rowboat, canoe, kayak","/m/06q74":"Motorboat, speedboat",
    "/m/014zdl":"Ship","/m/012f08":"Motor vehicle (road)","/m/0k4j":"Car",
    "/m/07qv_x5":"Vehicle horn, car horn, honking","/m/07pl1bw":"Toot",
    "/m/04xp5v":"Car alarm","/t/dd00134":"Power windows, electric windows",
    "/m/07rknqz":"Skidding","/m/07qf0zm":"Tire squeal",
    "/m/07qcpgn":"Car passing by","/m/07qqyl4":"Race car, auto racing",
    "/m/07rb2bh":"Truck","/m/07qb_dv":"Air brake",
    "/m/07q2z82":"Air horn, truck horn","/m/01g50p":"Reversing beeps",
    "/m/07rjzl8":"Ice cream truck, ice cream van","/m/012t_z":"Bus",
    "/m/01bjv":"Emergency vehicle","/m/02mk9":"Police car (siren)",
    "/m/04qvtq":"Ambulance (siren)",
    "/m/07rhhzj":"Fire engine, fire truck (siren)","/m/04_sv":"Motorcycle",
    "/m/0btp2":"Traffic noise, roadway noise","/m/07lk2q":"Rail transport",
    "/m/07jdr":"Train","/m/07r04":"Train whistle","/m/04229":"Train horn",
    "/m/0195fx":"Railroad car, train wagon",
    "/m/07qmpdm":"Train wheels squealing","/m/013cjv":"Subway, metro, underground",
    "/m/014yck":"Aircraft","/m/04229":"Aircraft engine","/m/02l6bg":"Jet engine",
    "/m/0mb7c":"Propeller, airscrew","/m/0cmf2":"Helicopter",
    "/m/03ldq":"Fixed-wing aircraft, airplane","/m/01g90h":"Bicycle",
    "/m/0dv3j":"Skateboard","/m/052_rw":"Engine",
    "/m/08j51y":"Light engine (high frequency)","/m/01sm1g":"Dental drill, dentist's drill",
    "/m/0hdsk":"Lawn mower","/m/068hy":"Chainsaw",
    "/m/07pb8fc":"Medium engine (mid frequency)",
    "/m/07q2z82":"Heavy engine (low frequency)","/m/07qqyl4":"Engine knocking",
    "/m/07rknqz":"Engine starting","/m/07rwm0c":"Idling",
    "/m/07s34ls":"Accelerating, revving, vroom","/m/02dgv":"Door",
    "/m/03wwcy":"Doorbell","/m/07r4wb8":"Ding-dong",
    "/m/07rqfr6":"Sliding door","/m/07q6cd_":"Slam","/m/07qnq_y":"Knock",
    "/m/07rdhzs":"Tap","/m/07qn4z3":"Squeak",
    "/m/01d3sd":"Cupboard open or close","/m/04brg2":"Drawer open or close",
    "/m/07r8lsr":"Dishes, pots, and pans","/m/04_sv":"Cutlery, silverware",
    "/m/07r5v4s":"Chopping (food)","/m/0f8s22":"Frying (food)",
    "/m/07gql":"Microwave oven","/m/02zdst":"Blender",
    "/m/07r4k75":"Water tap, faucet","/m/0130jx":"Sink (filling or washing)",
    "/m/07sq3zk":"Bathtub (filling or washing)","/m/03dnzn":"Hair dryer",
    "/m/01b9nn":"Toilet flush","/m/07ptfmf":"Toothbrush",
    "/m/02qldy":"Electric toothbrush","/m/04fgwm":"Vacuum cleaner",
    "/m/07qc9xj":"Zipper (clothing)","/m/02zsn":"Keys jangling",
    "/m/0242l":"Coin (dropping)","/m/01z5f":"Scissors",
    "/m/06_y0by":"Electric shaver, electric razor","/m/0llzx":"Shuffling cards",
    "/m/07qjznt":"Typing","/m/07qmklz":"Typewriter",
    "/m/01ljkq":"Computer keyboard","/m/07pp_mv":"Writing",
    "/m/07qqf1_":"Alarm","/m/015p6":"Telephone",
    "/m/06hps":"Telephone bell ringing","/m/0ytgt":"Ringtone",
    "/m/07pp8cl":"Telephone dialing, DTMF","/m/07pxg6x":"Dial tone",
    "/m/07qs1cx":"Busy signal","/m/0gvgw0":"Alarm clock","/m/03kmc9":"Siren",
    "/m/0dgbq":"Civil defense siren","/m/07qhfl_":"Buzzer",
    "/m/07qqt8h":"Smoke detector, smoke alarm","/m/09x0r":"Fire alarm",
    "/m/0dwtp":"Foghorn","/m/0l14l2":"Whistle","/m/07rjwbb":"Steam whistle",
    "/t/dd00077":"Mechanisms","/m/07qs1cx":"Ratchet, pawl",
    "/m/01x3z":"Clock","/m/07qmf1e":"Tick","/m/07plct2":"Tick-tock",
    "/m/07ph9y9":"Gears","/m/07s8j8t":"Pulleys","/m/0l15bq":"Sewing machine",
    "/m/07rknqz":"Mechanical fan","/m/07rkbfh":"Air conditioning",
    "/m/04179l":"Cash register","/m/07r4gkf":"Printer",
    "/m/07gsv":"Camera","/m/025rv6n":"Single-lens reflex camera",
    "/t/dd00058":"Tools","/m/03l9g":"Hammer","/m/07r4k75":"Jackhammer",
    "/m/07rknqz":"Sawing","/m/07qs1cx":"Filing (rasp)",
    "/m/07plct2":"Sanding","/m/07qgkxl":"Power tool","/m/014zdl":"Drill",
    "/m/032n05":"Explosion","/m/032n05":"Gunshot, gunfire",
    "/m/04229":"Machine gun","/m/07qqf1_":"Fusillade",
    "/m/07pl1bw":"Artillery fire","/m/07r66yr":"Cap gun",
    "/m/025_jnm":"Fireworks","/m/0bm02":"Firecracker",
    "/m/07q4ntr":"Burst, pop","/m/025rv6n":"Eruption","/m/07pl1bw":"Boom",
    "/m/04gy_2":"Wood","/m/07qjznt":"Chop","/m/01x3z":"Splinter",
    "/m/07qn4z3":"Crack","/m/07r04":"Glass",
    "/m/0242l":"Chink, clink","/m/07rrh0c":"Shatter","/m/07rjwbb":"Liquid",
    "/m/07qs1cx":"Splash, splatter","/m/07qnq_y":"Slosh",
    "/m/07rcgpl":"Squish","/m/07q6cd_":"Drip",
    "/m/07rqfr6":"Pour","/m/07qmpdm":"Trickle, dribble",
    "/m/07phhsh":"Gush","/m/07pl1bw":"Fill (with liquid)",
    "/m/07q4ntr":"Spray","/m/07r04":"Pump (liquid)","/m/06q74":"Stir",
    "/m/07rwm0c":"Boiling","/m/07s8j8t":"Sonar","/m/032n05":"Arrow",
    "/m/07r5v4s":"Whoosh, swoosh, swish","/m/07qnq_y":"Thump, thud",
    "/m/07q6cd_":"Thunk","/m/025_jnm":"Electronic tuner",
    "/m/0fx9l":"Effects unit","/m/09l8g":"Chorus effect",
    "/m/04brg2":"Basketball bounce","/m/07pb8fc":"Bang",
    "/m/07qhfl_":"Slap, smack","/m/07rrh0c":"Whack, thwack",
    "/m/07sr1lc":"Smash, crash","/m/07plct2":"Breaking",
    "/m/07q7njn":"Bouncing","/m/07r04":"Whip","/m/07rcgpl":"Flap",
    "/m/07r5v4s":"Scratch","/m/07qmpdm":"Scrape","/m/07s34ls":"Rub",
    "/m/07rknqz":"Roll","/m/07ph9y9":"Crushing",
    "/m/07qgkxl":"Crumpling, crinkling","/m/06hps":"Tearing",
    "/m/0dgbq":"Beep, bleep","/m/03wwcy":"Ping","/m/07rkbfh":"Ding",
    "/m/07r04":"Clang","/m/07qnq_y":"Squeal","/m/07q6cd_":"Creak",
    "/m/025_jnm":"Rustle","/m/07qb_dv":"Tinkle",
    "/m/07qs1cx":"Clatter","/m/07r4gkf":"Sizzle",
    "/m/025rv6n":"Clicking","/m/07qhfl_":"Clickety-clack",
    "/m/07rcgpl":"Rumble","/m/07q4ntr":"Plop",
    "/m/07rjwbb":"Jingle, tinkle","/m/07s2xch":"Hum",
    "/m/06q74":"Zing","/m/01g50p":"Boing",
    "/t/dd00125":"Crunch","/m/07qjznt":"Silence",
    "/m/07qs1cx":"Sine wave","/m/07qgkxl":"Harmonic",
    "/m/07r4k75":"Chirp tone","/m/07plft2":"Sound effect",
    "/t/dd00134":"Whir","/m/07pb8fc":"Clunk",
}

# Now build the correct mapping: BEATs index -> label name
print("=== BEATS INDEX -> CORRECT LABEL ===")
print()
correct_map = {}
for beats_idx, mid in label_dict.items():
    name = YAMNET_ID_TO_NAME.get(mid, "UNKNOWN_" + str(mid))
    correct_map[beats_idx] = name

# Print first 20 and key music indices
print("First 20:")
for i in range(20):
    print(str(i) + " -> " + str(label_dict[i]) + " -> " + correct_map.get(i, "?"))

print()
print("Key music class indices (searching for Plucked string, Guitar, Vocals etc):")
for idx, mid in label_dict.items():
    name = YAMNET_ID_TO_NAME.get(mid, "")
    if any(k in name.lower() for k in ["pluck","guitar","vocal","sing","drum","tabla",
                                        "piano","flute","violin","bass","music","sitar",
                                        "keyboard","percussion","cello","harp"]):
        print(str(idx) + " -> " + mid + " -> " + name)

